<table style="border-collapse: collapse;">
    <tr>
        <td style="padding: 4px 12px 4px 0;"><b>Email</b></td>
        <td style="padding: 4px 0;">:</td>
        <td style="padding: 4px 0;">syahkirapkp@gmail.com</td>
    </tr>
    <tr>
        <td style="padding: 4px 12px 4px 0;"><b>Instagram</b></td>
        <td style="padding: 4px 0;">:</td>
        <td style="padding: 4px 0;">syahkiradz</td>
    </tr>
    <tr>
        <td style="padding: 4px 12px 4px 0;"><b>WhatsApp</b></td>
        <td style="padding: 4px 0;">:</td>
        <td style="padding: 4px 0;">0831 8077 6164</td>
    </tr>
    <tr>
        <td style="padding: 4px 12px 4px 0;"><b>Alamat</b></td>
        <td style="padding: 4px 0;">:</td>
        <td style="padding: 4px 0;">JL. Fatmawati, Gg. Sanggar Warisan Budaya</td>
    </tr>
</table>