<?php
<ul>
    <li style="text-align: justify; margin-bottom: 16px;">
        <strong>Usaha jualan brownies lumer (individu).</strong><br>
        Memenuhi tugas akhir di kelas 12 membuka usaha dengan berjualan brownies cup pada event bazar yang disediakan oleh sekolah. Pada event tersebut terjual 50 cup brownies dengan bersih diperoleh &gt;50rb perhari yang diadakan selama 3 hari.
    </li>
    <li style="text-align: justify;">
        <strong>Usaha jualan piscok lumer (kelompok).</strong><br>
        Memenuhi tugas di kelas 11 membuka usaha dengan berjualan piscok lumer pada jam istirahat memanfaatkan waktu untuk berjualan di kelas-kelas. Pada kegiatan tersebut terjual 20 cup dengan bersih diperoleh &gt;30rb perhari yang dilaksanakan selama 1 bulan.
    </li>
</ul>
