<?php
<p><b>Kasir (Praktek Kerja Lapangan)</b><br>
PT RAMAYANA LESTARI SENTOSA TBK PANGKALPINANG
<ul style="margin-top: 8px; margin-bottom: 8px; margin-left: 0; padding-left: 20px;">
    <li style="text-align: justify;">Menghimpun puluhan transaksi penjualan per hari secara tunai, debit, atau kredit dengan akurat untuk menunjang operasional bisnis.</li>
    <li style="text-align: justify;">Menginput seluruh setoran kasir yang didapatkan mulai dari uang tunai dan faktur EDC. Sesuai shift kerja.</li>
    <li style="text-align: justify;">Sukses menekan complain pelanggan dengan senantiasa memberi informasi dan promosi lewat pengetahuan produk yang ada.</li>
</ul>
</p>

<p><b>Pramuniaga (Pengalaman Mandiri)</b><br>
TOKO AKSESORIS SIMPANG DKT
<ul style="margin-top: 8px; margin-bottom: 8px; margin-left: 0; padding-left: 20px;">
    <li style="text-align: justify;">Mencatat kegiatan transaksi penjualan toko, dengan mencatat >10 transaksi 
penjualan untuk mendapati data penjualan toko.</li>
    <li style="text-align: justify;">Mengorganisir letak penyimpanan > 20 produk toko demi menciptakan visual yang 
baik.</li>
    <li style="text-align: justify;">Memberikan pelayanan terbaik kepada pembeli di toko setiap hari demi menjamin 
kepuasan keplanggan.</li>
</ul>
</p>

<p><b>Pramuniaga fresh product  (Pengalaman Mandiri)</b><br>
MM ACING JAYA METRO KAMPAK
<ul style="margin-top: 8px; margin-bottom: 8px; margin-left: 0; padding-left: 20px;">
    <li style="text-align: justify;">Menerima produk buah yang baru datang dari pemasok, memastikan kualitas dan 
kondisi produk sesuai standar.</li>
    <li style="text-align: justify;">Memproduksi olahan buah menjadi buah potong, jus buah, salad buah, rujak, 
impulse water, es krim, dan asinan.</li>
    <li style="text-align: justify;">Mengelola akun promosi toko, dengan manajemen akun media sosial dan 
pembuatan konten kreatif.</li>
 <li style="text-align: justify;">Berhasil mengantarkan orderan produk fresh > 30 orderan dalam seminggu dari 
puluhan titik penerima di kota pangkalpinang.</li>
</ul>
</p>
